### PR TITLE
Enables iframe embeddable OHM maps

### PR DESCRIPTION
**Pull request by erictheise**
Finishes https://github.com/OpenHistoricalMap/issues/issues/485 by leveraging updated MapLibre and addressing feedback about incorporating bbox into hash. Note that this works in concert with a PR on ohm-embed-1yr.

### CODE REVIEW

**Comment by erictheise** [comment]
The added text in the README relates to getting started in general, not to this particular issue. I can create a separate PR for that if need be.

**Review by danrademacher — APPROVED** [review]
Tested locally and working as expected, confirmed embed functioning in FF and Chrome in test iframe

**Comment by danrademacher** [comment]
Hmm, this worked great locally, but when I pushed to staging we get this in the embed code:
```
src="null#map=18/37.90620/-122.54747&layers=OD&date=1924-01-01&daterange=1924-01-01,2024-12-31&bbox=-122.5507414340973,37.90455187975752,-122.54419684410097,37.90784062588392"
```

So this line in the config is not getting picked up on deploy:
https://github.com/OpenHistoricalMap/ohm-website/pull/207/files/761cd9c9fcb98775a411cd0429bb559e6736b1b2#diff-e769bbb8c1ba3711c5403b424ed9c218ffafba7f1890ee394717196f28ff4540R4

**Comment by erictheise** [comment]
Apologies if this is obvious but `embed_server_url` is a new environment variable and it needs to be introduced into the `staging` (and `production`) environments. I don't know if they use `config/settings.local.yml` or if there's some other way of setting their environment variables.

**Pull request merged**
