### PR TITLE
Update iD to latest from OHM iD fork

### PR DESCRIPTION
**Pull request by danrademacher**
Latest changes from @erictheise upstream catchup in https://github.com/OpenHistoricalMap/iD/pull/194

### CODE REVIEW

**Comment by danrademacher** [comment]
@erictheise I tested this locally in OHM Rails context and itt seems fine for Staging deploy. If you could give it one more look, that would be great.

Then we merge and deploy.

though if you see a fix for https://github.com/OpenHistoricalMap/issues/issues/714 that we could roll into the staging deploy, that would be dandy.

**Comment by 1ec5** [comment]
Please make sure to address OpenHistoricalMap/issues#723 as well.

**Review by erictheise — APPROVED** [review]
The field width and missing icon issues have been addressed.

**Comment by 1ec5** [comment]
Can you also sync with OpenHistoricalMap/iD@eeec11e52b002e770b7537b409f550c1d7c3432f as a followup to OpenHistoricalMap/iD#193? Thanks!

**Comment by danrademacher** [comment]
So to close this out, we need to pull in https://github.com/OpenHistoricalMap/iD/commit/eeec11e52b002e770b7537b409f550c1d7c3432f

We also have this open PR we could potentially merge and get into next web iD deploy:
https://github.com/OpenHistoricalMap/iD/pull/196

**Comment by erictheise** [comment]
`git log` says that https://github.com/OpenHistoricalMap/iD/commit/eeec11e52b002e770b7537b409f550c1d7c3432f is already in `staging`.

**Comment by erictheise** [comment]
I don't think there's anything left to do @danrademacher.

**Pull request merged**
