### PR TITLE
Remove communities view and remove from nav

### PR DESCRIPTION
**Pull request by danrademacher**
@gregallensworth since your local dev is working, can you test this and see if it works locally?

The goal is simply that this link is gone form navbar:
image

And this route doesn't exist:
https://staging.openhistoricalmap.org/communities

That would check off another box on PR #153

### CODE REVIEW

**Comment by gregallensworth** [comment]
- [x] The link is indeed absent from the main header. 
  - [ ] But is still present about 20 lines down in **header.html.erb**; look for `communities_path` for the dropdown-menu version of this same link
- [ ] A direct call to http://localhost:3000/communities fails...
  - [x] giving an error that the template is missing,
  - [ ] but still exists, meaning the route was not deleted. Look for:
  - [ ] `communities` in `app/abilities/ability.rb` (a mention)
  - [ ] `app/controllers/site_controller.rb` (a three-line function)
  - [ ] `config/routes.rb` (one line)
- [ ] ??? I am also seeing in your commit the db structure SQL. Should that also be changing to remove this page & link?

**Comment by danrademacher** [comment]
Gah, this was an accidental inclusion in my commit:
>- [ ] ??? I am also seeing in your commit the db structure SQL. Should that also be changing to remove this page & link?

It seems like we should gitignore that file, but let me check with Devseed on that.

**Comment by danrademacher** [comment]
My local dev is still giving me errors on `master` and ant branches from `master`

while I sort that out, @gregallensworth can you go ahead and make all code changes needed as you listed them to remove /communities.

then we can have @Rub21 or @geohacker review and merge into #153 and see if we can get that PR merged and deployed sooner than later.

**Comment by gregallensworth** [comment]
> My local dev is still giving me errors on `master` and ant branches from `master`
> while I sort that out, @gregallensworth can you go ahead and make all code changes needed as you listed them to remove /communities.

Done.

I also reverted the **db/structure.sql** file to the one from `master` so it does not appear in this PR anymore.

**Review by batpad — APPROVED** [review]

**Pull request merged**
