### PR TITLE
598 remove public domain checkbox

### PR DESCRIPTION
**Pull request by erictheise**
This PR addresses  https://github.com/OpenHistoricalMap/issues/issues/598 by

- removing the `div` containing the `consider_pd` boolean
- modifying three controller tests to ensure that there's no regression in the view
- creating a migration that defaults `consider_pd` to `true` as that's implicit in our Terms of Use.

Some updated upstream values in `en.yml` were ported over to get tests to run before the checkbox was removed. They should present no conflict when a full upstream merge is performed.

The following tests will fail in the current version of `staging` as the checkbox exists but will pass in this branch:

```
rails test -v test/controllers/users_controller_test.rb -n "test_terms_new_user"
rails test -v test/controllers/users_controller_test.rb -n "test_terms_not_seen_with_referer"
rails test -v test/controllers/users_controller_test.rb -n "test_terms_not_seen_without_referer"
```

Feedback welcome.

### CODE REVIEW

**Comment by erictheise** [comment]
This would allow us to close #11, which I bumped into during last week's planning/triage.

**Comment by 1ec5** [comment]
This looks fine at a code level. I’m not very familiar with the database portion but it looks reasonable. Would you mind posting a screenshot of the resulting screen? I want to make sure users still wind up agreeing to what we expect. If I remember correctly, there was also a rough edge further up where we display the contributor terms by region.

**Comment by erictheise** [comment]
The checkbox in question used to be below the Continue / Cancel buttons as seen in the [original issue](https://github.com/OpenHistoricalMap/issues/issues/598). This screenshot scrolls the Public Domain section of the Terms of Use into the textarea.

image

**Comment by erictheise** [comment]
I see what you're saying about rough edges and contributor terms by region. My being in the "Rest of the world" struck me as odd the first time I saw it but then it faded into the background.

**Comment by 1ec5** [comment]
Thanks, I think it’s clear enough that the contributions are being released into the public domain (and not just “considered” under protest to be PD as in OSM).

We could probably tighten up some stuff, like explicitly naming the CC0 dedication and updating the URL to the contributors page (which is currently a redirect). The line under “Terms of Use” refers to OSMF infrastructure, but the OSMF isn’t involved here. These should be small changes as well but can be handled separately.

The definition of an active contributor is a bit of a non-sequitur, but only because we aren’t using that term for anything yet. Hopefully the summary and translation links point somewhere useful. If we don’t have OHM-specific wiki pages for them yet, I can start get them started with placeholder content.

**Review by 1ec5 — APPROVED** [review]

**Pull request merged**
