### PR TITLE
Upstream catchup

### PR DESCRIPTION
**Pull request by geohacker**
Previously #153 

This is a new round of upstream catchup. In this PR we'll work through applying OHM related changes and then merge to staging.

### CODE REVIEW

**Comment by geohacker** [comment]
@danrademacher @gregallensworth this is ready for you to look at. The steps I recommend are here:

1. First see all the conflicts `git status -s | grep '^UU'`
2. Any changes in the vendor/assets/iD should be replaced by ohm changes. So run `git checkout --theirs vendor/assets/iD`
3. Then `git add vendor/assets/iD`
4. Next look at config/locales/ — use the same approach as above.
5. Now go through the handful of files in an editor. I like VSCode because I can easily pick the change I want and combine.
6. Inspect the conflict and pull in changes that are needed on the OHM side. They are mostly straightforward
7. Complete conflict resolution and then push to `master`

I've gone through above and outside of iD and locales there are only these conflicts:

```
UU app/assets/javascripts/index/search.js
UU app/views/site/about.html.erb
UU app/views/site/copyright.html.erb
UU app/views/site/help.html.erb
```

I'm adding a patch for `app/assets/javascripts/index/search.js` here: 
[index-search.js.patch](https://github.com/OpenHistoricalMap/ohm-website/files/11220243/index-search.js.patch)

Once you resolve the conflicts, please commit to this branch and then we can test everything. Thank you!

cc @batpad @Rub21 @jeffreyameyer

**Comment by danrademacher** [comment]
Thank you @geohacker! We'll take a look at this soon and move it along

**Comment by danrademacher** [comment]
OK, now that I have local dev sorted, I'm digging into the conflicts for the three files below and I think these should be reasonably quick to resolve, but there's some dependency between the locales files and these that we need to sort of
```
UU app/views/site/about.html.erb
UU app/views/site/copyright.html.erb
UU app/views/site/help.html.erb
```

When I try applying the patch, I get this:
```
% git apply patch.patch
error: unrecognized input
```

@geohacker how did you patch the locales files en masse?

From what I see, the changes to the `.erb` files are a mix of 
1. CSS changes (probably for new bootstrap or something, so we should defer to upstream)
2. HTML changes (minor, easy, also defer to upstream)
3. changes in the `key` values that are tied to the locales files, where sometimes we want to stick with staging but in other cases we might want to defer to upstream and revise our locale files to match upstream and make future catchup simpler

That third batch is a bit more tricky and I think requires bouncing back and forth between the erb file and the locale file to figure out where we need to favor upstream and reqrite our locale info and where we should favor our locale file and stick with what's in staging for the erb.

Anyway, ideally, I'd apply that patch for search + locales and then finish by resolving our three files and assessing if there are further  changes needed in the locale files

**Comment by geohacker** [comment]
> how did you patch the locales files en masse?

Ah looks like some issues with the way I created the patch. The patches for locale and iD fixes actually didnt have any changes so those were invalid. I think locally you can follow the --theirs step as described above for those.

For the search.js file, please use 
[search.patch](https://github.com/OpenHistoricalMap/ohm-website/files/11292723/search.patch)

I had to:
1. resolve conflict
2. git add
3. and then `git diff --staged --no-color app/assets/javascripts/index/search.js > /tmp/search.patch`
4. to apply, run `git apply --whitespace=fix /tmp/search.patch`

**Comment by danrademacher** [comment]
OK, this mostly worked as advertised, and was pretty easy. 

But it;s not quite ready -- the About page had a ton of both HTML/CSS changes and changes to the keys for the locale files. It seemed easier to just accept the `master` upstream OSM changes, and now I need to sort out the About key changes. Currently About looks like this because of a lot of lost keys:
image

Once I do that for `en.yml` I am not sure how to handle all the other languages...

**Comment by danrademacher** [comment]
Maybe this would be our chance to fix that broken alignment at the top and add an OHM-specific image, too!

**Comment by danrademacher** [comment]
Actually, a few other things I need to clean up, on copyright page:
image

**Comment by danrademacher** [comment]
But good to see the sidebar and map styles showing up, timeline working! Also checked and confirmed that iD is using our version with the date filter section.
image

So cleaning up some locale stuff on glorified HTML pages is a great place to be -- even easier than the last round, which was easier than the previous one!

**Comment by danrademacher** [comment]
This is now working locally as far as I can tell, with all merges resolved. @Rub21 I think next step would be to deploy to staging.openhistoricalmap.org  and run through [the testing checklist](https://paper.dropbox.com/doc/OHM-website-testing-checklist--B3LZcJxmQcAowUVa6YpaSIJTAg-CLKMfq6NMiA0LQD5SkGMe) that @karitop made.

does that sound right?

**Comment by danrademacher** [comment]
Though I wonder if we should go ahead at and also do a catchup to upstream iD, to keep both website and iD more in sync with latest changes. I am going to make a draft PR in our iD and see how easily we can get latest in there.

**Comment by danrademacher** [comment]
Ok, working on the iD upstream catchup over here: https://github.com/OpenHistoricalMap/iD/pull/177

**Comment by danrademacher** [comment]
Shifting this to ready to deploy to staging.

@Rub21 to coordinate to get this testing
> through [the testing checklist](https://paper.dropbox.com/doc/OHM-website-testing-checklist--B3LZcJxmQcAowUVa6YpaSIJTAg-CLKMfq6NMiA0LQD5SkGMe) that @karitotp made.

**Comment by danrademacher** [comment]
Shifting this to ready to deploy to staging.

@Rub21 to coordinate to get this deployed to staging and over to testing through [the testing checklist](https://paper.dropbox.com/doc/OHM-website-testing-checklist--B3LZcJxmQcAowUVa6YpaSIJTAg-CLKMfq6NMiA0LQD5SkGMe) that @karitotp made.

**Comment by Rub21** [comment]
@danrademacher , I have just deploy the latest changes https://github.com/OpenHistoricalMap/ohm-website/tree/f3a0224fd9e975585433069795212f63d860fd6d  in staging.  https://staging.openhistoricalmap.org/. 

@karitotp , could you do the testing according to the [checklist](https://paper.dropbox.com/doc/OHM-website-testing-checklist--B3LZcJxmQcAowUVa6YpaSIJTAg-CLKMfq6NMiA0LQD5SkGMe) ?

**Comment by karitotp** [comment]
@Rub21 @danrademacher, I did the tests and all functionalities of the checklist work good :+1: (except for the "Minute replication reflects the changesets" and "Taginfo" items, which I could not test).

The only thing that I found are some "Html" text instead to display the user-name, dates or something else, on the following pages:
- The sign-up page
Screenshot from 2023-05-03 12-08-14
- The list of changesets on the History page, the list of changesets on My edits, and the Changesets details
Selection_850
- On the sidebar for adding a note to the map
Selection_848

**Comment by danrademacher** [comment]
Thanks @karitotp! Looks like we need to add a few more new keys to our locales file. I'm out of office today but I'll get that done on Monday and then we can deploy this to production

**Comment by danrademacher** [comment]
Ok, those issues are resolved in [this commmit](https://github.com/OpenHistoricalMap/ohm-website/pull/173/commits/a2cb6499a1d03197fb82dfb57e2ea815c2945b97). @Rub21 if you could redeploy to staging, then we'll confirm and if all looks good, proceed with the merge and production deploy.

Managing the locales file is an interesting challenge. Not hard but I think each time we do an upstream catchup, we should look at commits since last update on the en.yml locales file to catch evolving keys or moving YML structure in that file, which was most of the issue here, as opposed to new features with now strings.

**Comment by Rub21** [comment]
@karitotp , could you take  one final review on the staging site https://staging.openhistoricalmap.org/

**Comment by karitotp** [comment]
@Rub21, everything is working well, I only found these cases:

- In the date filter of Photo Overlays, the "from" date takes the same mm/dd from the "To" date, and the year change to 0002.  This occurs when dates are entered without using the date picker option, and when the "from" date is entered before the "To" date.

https://github.com/OpenHistoricalMap/ohm-website/assets/11504548/acbb82a0-58db-4ecc-8ddc-7e87a6243176

- Apparently there are some missing keys in:
  - The title of the list of changesets on My Edits page
Selection_860

  - [My traces](https://staging.openhistoricalmap.org/user/karitotp/traces) page from GPS Traces 
Selection_861

**Comment by danrademacher** [comment]
OK, I resolved the missing keys on the My Traces and My Edits areas.

Since the other bug is specific to iD, I think we should track that as we update iD. Also, the video embed in the comment doesn't work for me and I had trouble reproducing the issue

**Review by danrademacher — APPROVED** [review]

**Pull request merged**
