### PR TITLE
Upstream catchup

### PR DESCRIPTION
**Pull request by geohacker**
I'm trying a standard, manual workflow of merging upstream changes.  Will try to outline the steps here:

1. Create a master branch in this repo
2. Use the 'Sync Fork' feature on Github using the master branch — this will require us to remove any changes on our side and then automatically bring in changes from openstreetmap-website:master
3. Create a PR from ohm-website:master to ohm-website:staging — this will now show a lot of conflicts
4. Now update `staging` locally using `git pull origin staging`
5. Now pull master locally using `git checkout master`
6. Start a merge using `git merge staging`. At this point we need to start working through conflicts.

The strategy I used for conflict resolution is pretty manual but is more reliable:
1. First see all the conflicts `git status -s | grep '^UU'`
2. Any changes in the vendor/assets/iD should be replaced by ohm changes. So run `git checkout --theirs vendor/assets/iD`
3. Then `git add vendor/assets/iD`
4. Next look at config/locales/ — use the same approach as above.
5. Now go through the handful of files in an editor. I like VSCode because I can easily pick the change I want and combine.
6. Inspect the conflict and pull in changes that are needed on the OHM side. They are mostly straightforward
7. Complete conflict resolution and then push to `master`

### CODE REVIEW

**Comment by geohacker** [comment]
This PR is now ready for review + local testing @batpad @danrademacher @rub21. It also contains upstream iD updates for v2.24.1 as prepared in this PR https://github.com/OpenHistoricalMap/iD/pull/168.

I've tested it all together locally and things look good to me.

cc @jeffreyameyer

**Comment by danrademacher** [comment]
On first load, things are looking great here.

A few questions:
* I noticed a lot of documentation changes, eg to https://github.com/OpenHistoricalMap/ohm-website/pull/153/files#diff-7b529b3af70da49fbbf1f49523d108b62b1cfe4ee42175a0bbab967b6f11c92e. I wonder if we need to try a complete fresh install of this stack to make sure local dev is still working as expected?
* I never quite know if some connected services are expected to work in local testing -- like right now, searching on the local site returns an error of "Error contacting nomin-publi-15vpg1m703pp9-1297651006.us-east-1.elb.amazonaws.com: 503". Looks like that might be a wrong setting setting in config/settings.yml, which isn't even changed in this PR...

**Comment by geohacker** [comment]
@danrademacher

> I wonder if we need to try a complete fresh install of this stack to make sure local dev is still working as expected?

I recommend we keep the openstreetmap-website docs as is and create a new readme for ohm docs. It just helps track required changes. I am running a local stack and things look good to me but it'll be great if you can test as well!

> I never quite know if some connected services are expected to work in local testing

Those are coming from your settings.yml or settings.local.yml. We can fix them in settings.yml and commit here if you think that'd help but keeping them in your settings.local.yml is what I'd recommend.

**Comment by geohacker** [comment]
If everyone has had a chance to review this, we could merge and deploy to production.

**Comment by danrademacher** [comment]
Taking another look -- and I noticed staging Overpass has been down for a while per
https://stats.uptimerobot.com/0BBDoIkXKJ/792483705

I also just pulled this checklist out of https://github.com/OpenHistoricalMap/issues/issues/422

- [ ] Full round trip editing:
  - Open iD from application
  - Make an edit with something we know is symbolized clearly on the map
  - Save the edit
  - View the changeset and note if session persists
  - Confirm that the edit is appearing in the vector tiles in a timely manner
- [ ] Check every URL route on the site, navigating between them and confirming that login is respected
- [ ] Test searches on Nominatim, for a known working thing
- [ ] Add something new to OSM that Nominatim will search, then confirm it is searchable
- [ ] Use overpass turbo to query Overpass to confirm that new edits are showing up
- [ ] Edit in JOSM and confirm we can push to staging.
- [ ] Confirm TagInfo is consuming and updating diffs

**Comment by danrademacher** [comment]
Some notes of things we need to do:
* Disable https://staging.openhistoricalmap.org/communities -- it is not on the top nav of production and we don't have anything to put there
* Fix our injection of Inspector panel, since it looks like something has changed 
image
* confirm that this edit shows up in tiles, Nominatim, and Overpass -- https://staging.openhistoricalmap.org/changeset/39698#map=16/37.8696/-122.2615&layers=OD&date=1923-01-01&daterange=1923-01-01,2023-12-31

**Comment by Rub21** [comment]
I have been trying to do some editions in JOSM  the staging api , but it didn't work ,  I have tried the different methods to authenticate in JOSM but does not work, the [server logs](https://gist.github.com/Rub21/397db79ffbd02ee8b909796b8214ecb8) ,... looking  the issue as well.


image

**Comment by geohacker** [comment]
The JOSM issue is fixed now https://staging.openhistoricalmap.org/changeset/39701#map=18/55.76488/-3.66855&layers=O&date=1923-01-01&daterange=1923-01-01,2023-12-31

The basic http method is now optionally enabled via an env in the settings.yml. I just set that to true https://github.com/OpenHistoricalMap/ohm-deploy/commit/900b1eb988160bbcb81813c707975837fd8374a0

**Comment by Rub21** [comment]
> confirm that [this edit](https://staging.openhistoricalmap.org/changeset/39698#map=16/37.8696/-122.2615&layers=OD&date=1923-01-01&daterange=1923-01-01,2023-12-31) shows up in tiles, Nominatim, and Overpass -- I waited 10 minutes and I don't see my Test Stadium building test edit in [map tiles](https://vtiles-staging.openhistoricalmap.org/#15.26/37.873144/-122.271026), [Nominatim](https://nominatim-staging.openhistoricalmap.org/search.html?q=Test+stadium), [Overpass Turbo](https://overpass-turbo-staging.openhistoricalmap.org/?q=LyoKVGhpcyBoYcSGYmVlbiBnxI1lcmF0ZWQgYnkgdGhlIG92xJJwxIlzLXR1cmJvIHdpemFyZC7EgsSdxJ9yaWdpbmFsIHNlxLBjaMSsxIk6CsOiwoDCnMS7bWU9IlRlc3QgU3RhZGl1bSLFiMKdCiovCltvdXQ6anNvbl1bdGnFjMWkxaYyNV07Ci8vxI_ElMSdciByxZF1bHRzCigKICDFuCBxdcSSxJrEo3LFk2ZvcjogxYjFimHFjMWOxZDFksWUxZbFmMWaxZzCgMWexohub2RlWyLFi2UixpzFkcWTxZXFl8WZxZtdKHt7YsSqeH19KcW2xoh3YXnGq8atxq_Fj8axxp_GtMaixrfGuca7b8a9xr_HgcW-ZWzElGnFqseGxprGrsawxp7Gs8ahxrbGuMa6xrzGvseACsenxopwxLduxZPFv3PGgcaDCsWxxJjGqHnFtj7Ftse0c2vHlsaLdDs&c=AXvtmsrwMI)

Confirming that the staging edition goes to the tiler, nominatim and overpass , There is an issue that happens very rarely in file replication, this issue is about  that some replication files are not generated and the sequence is lost, so as consequence the the other apps can no be able to update the data.

**Comment by danrademacher** [comment]
Feels like we have lost a bit of momentum here -- between my hand injury and now my local dev is failing with new errors (unique to me so far, noted at https://greeninfo.slack.com/archives/CACTQ7MU4/p1675972123788309/), I've had a hard time keeping up with this.

* We have a PR in process at #155 to fix the /communities info
* Doing this process again and accidentally committing changes to `db/structure.sql` makes me want to figure out if we can `git ignore` that file or take some other action to avoid accidental commits that include automated and seemingly irrelevant changes

Seems like the only [other unchecked box here](https://github.com/OpenHistoricalMap/ohm-website/pull/153#issuecomment-1420206577) is to confirm that Taginfo is consuming diffs.

@Rub21 can you take a look and make sure Taginfo staging is consuming diffs as expected and if so, check that off?

**Comment by geohacker** [comment]
@danrademacher could you post here or in a new ticket what the local Dev problem you're running into is? I'm not able to access that Slack link.

Regarding the structure.sql, like mentioned in the other ticket, we cannot gitignore as it's required to keep up with migrations.

**Comment by danrademacher** [comment]
New ticket on local dev here: https://github.com/OpenHistoricalMap/issues/issues/516

**Comment by danrademacher** [comment]
Ok, I believe that once this child PR is reviewed and merged: https://github.com/OpenHistoricalMap/ohm-website/pull/155, then we can merge and deploy this upstream catchup PR

**Comment by danrademacher** [comment]
Per @batpad on Slack, we're going to hold on deploy for this until next week.

I am on the fence of whether we need to do another round of full testing on this before deploy:

- [ ] Full round trip editing:
  - Open iD from application
  - Make an edit with something we know is symbolized clearly on the map
  - Save the edit
  - View the changeset and note if session persists
  - Confirm that the edit is appearing in the vector tiles in a timely manner
- [ ] Check every URL route on the site, navigating between them and confirming that login is respected
- [ ] Test searches on Nominatim, for a known working thing
- [ ] Add something new to OHM that Nominatim will search, then confirm it is searchable
- [ ] Use overpass turbo to query Overpass to confirm that new edits are showing up
- [ ] Edit in JOSM and confirm we can push to staging.
- [ ] Confirm TagInfo is consuming and updating diffs

**Comment by danrademacher** [comment]
@Rub21 this is the same checklist we used a few weeks ago on this PR:

- [ ] Full round trip editing:
  - Open iD from application
  - Make an edit with something we know is symbolized clearly on the map
  - Save the edit
  - View the changeset and note if session persists
  - Confirm that the edit is appearing in the vector tiles in a timely manner
- [ ] Check every URL route on the site, navigating between them and confirming that login is respected
- [ ] Test searches on Nominatim, for a known working thing
- [ ] Add something new to OHM that Nominatim will search, then confirm it is searchable
- [ ] Use overpass turbo to query Overpass to confirm that new edits are showing up
- [ ] Edit in JOSM and confirm we can push to staging.
- [ ] Confirm TagInfo is consuming and updating diffs

**Comment by Rub21** [comment]
Issues that I found so far: 
- Confirmation email is returning with example.com
- Shows links to OSM in  https://staging.openhistoricalmap.org/help

**Comment by Rub21** [comment]
> Confirmation email is returning with example.com

I fixed that ,  it is sending  the email with the right name and links

> Shows links to OSM in https://staging.openhistoricalmap.org/help

PR: https://github.com/OpenHistoricalMap/ohm-website/pull/162

**Review by danrademacher — APPROVED** [review]
Based on DevSeed testing of all services and shared review of content changes, this seems ready to deploy

**Review by Rub21 — APPROVED** [review]

**Pull request merged**
