### PR TITLE
Addresses #485 by generating src url according to spec.

### PR DESCRIPTION
**Pull request by erictheise**
My first PR here so I'm not sure who picks reviewers, how changes are tested, or which branch to merge against.

This is for https://github.com/OpenHistoricalMap/issues/issues/485.

### CODE REVIEW

**Comment by danrademacher** [comment]
I noted the base URL wasn't working as supplied, so fixed that in https://github.com/OpenHistoricalMap/ohm-website/pull/186/commits/ff16a073ab8f55dae7c6fb9854ef62002569d338. Just the thing where a raw Github.io link includes the repo in it, but the custom domain version does not.

Another thing I noticed in local testing is that the URL comes through with the `&` encoded as `&amp;`, which seems to break the embed filter.

Here's the embed `src` link as supplied:
`https://embed.openhistoricalmap.org/#map=14/39.2456/-84.3049&amp;date=1923-01-01`

That looks like this:
image

Here's the unencoded parameter:
`https://embed.openhistoricalmap.org/#map=14/39.2456/-84.3049&date=1923-01-01`
image

The second one matches what we expect form the website:
https://www.openhistoricalmap.org/#map=14/39.2456/-84.2942&layers=O&date=1923-01-01&daterange=1923-01-01,2023-12-31

**Comment by erictheise** [comment]
Having just embedded a selection of maps into a blog post I can say that this does not spark joy, and is not ready to be merged. I need to review how this feature behaves upstream, but we have at least problem of our own that must be addressed.

**Comment by danrademacher** [comment]
I see what you mean about the embed. 

When I thought I would get a river and some bridges, I get this instead:
image

Seems like the embed is not actually centering.

One element I had lost track of here is the map marker option

https://embed.openhistoricalmap.org/#map=11/39.2377/-84.3025&date=1923-01-01&mlat=39.2377&mlon=-84.3025
produces this view:
image

So if this checkbox is checked:
image

We should append `&mlat=LAT&mlon=LON` where the lat and lon match the same one we give as map centerpoint

Interestingly, if I embed with those params in place, I DO get map I was expecting:
image

I suspect then that the centering issue is more in the embed code itself and not in the website code.

If that's the case, then we could add the map marker logic and call this done as far as website code is concerned, then fix the embed code and finally merge and deploy

**Comment by erictheise** [comment]
This got messy with the upstream merge so I've created a second branch and will create a new pull request.

**Pull request closed without merging**
